local options = {
	number = true,
	cursorline = true,
	signcolumn = 'yes',
	ttimeoutlen = 10,
  timeoutlen = 500,
	numberwidth = 4,
	mouse = 'a',
	title = true,
	autoindent = true,
	smartindent = true,
	hlsearch = true,
	incsearch = true,
	ignorecase = true,
	smartcase = true,
	wrapscan = true,
	backup = false,
	showcmd = false,
	cmdheight = 1,
	laststatus = 2,
	expandtab = true,
	shell = 'zsh',
	smarttab = true,
	breakindent = true,
	shiftwidth = 2,
	tabstop = 2,
	wrap = false,
	termguicolors = true,
  clipboard = 'unnamedplus',
  conceallevel = 0,
  pumheight = 10,
  showmode = false,
  splitbelow = true,
  splitright = true,
  scrolloff = 8,
  sidescrolloff = 8,
  whichwrap = 'b,s,<,>,[,]',
}

for k, v in pairs(options) do
	vim.opt[k] = v
end
